### PR TITLE
Support Deploy Through GitHub Actions

### PR DESCRIPTION
**Pull request by dshanske**
Seems simple enough

### CODE REVIEW

**Comment by pfefferle** [comment]
The `.wordpress-org` folder including the assets from the SVN is missing

**Comment by dshanske** [comment]
Oops, forgot...pushed now.

**Review by pfefferle — APPROVED** [review]
Does the `.distignore` file do what I think it should do? Never heard about that!

**Comment by dshanske** [comment]
@pfefferle According to the 10up instructions

**Comment by pfefferle** [comment]
You should also delete the `.svnignore`

**Pull request merged**
