### PR TITLE
Add mf2 meta

### LINKED ISSUE #3: JSON Doesn't Include MF2 Properties
The JSON doesn't include any MF2 properties, stored with the mf2 prefix in post meta. That is a problem as that is where I store most of my stuff for Post Kinds and where Micropub stores its properties.

### PR DESCRIPTION
**Pull request by pfefferle**
@dshanske I do not use a plugin thatt writes `mf2_*` metas, so can you verify that it works?

fixes #3

### CODE REVIEW

**Comment by dshanske** [comment]
The MF2 looks good, some of the JF2 isn't collapsed. Micropub and Post Kinds store as MF2. I used to store in Post Kinds as JF2 but changed to match for consistency....I used to store single properties, but switched to storing all properties as arrays.

**Review by dshanske — CHANGES_REQUESTED** [review]
If you fix the collapsing of single valued properties in the jf2 rendition, this will be fine. You can test by installing Micropub and making a post.

**Comment by pfefferle** [comment]
@dshanske the mf2 seems to be completely broken... I tested the meta of post-kinds and parts are mf2 and parts are jf2... that means I have to completly normalize the data :(

```JSON
"in-reply-to": {
                "type": [
                    "h-cite"
                ],
                "properties": {
                    "published": [
                        "2018-06-19T21:44:20+00:00"
                    ],
                    "updated": [
                        "2018-06-19T21:44:20+00:00"
                    ],
                    "summary": [
                        "(Ich wei\u00df, ich wei\u00df\u2026 ich bin etwas sp\u00e4t dran, aber immerhin schreibe ich schon seit dem 26. Mai an dem Post!)\r\nAm 27.06. fand, im Rahmen des Karlsruher WordPress Meetups, eine kleine 15 Jahr feier statt. Lucas Radke (der leider keine eigene Webseite besitzt) hat zu diesem Anlass, die WordPress H..."
                    ],
                    "name": [
                        "15 Jahre WordPress"
                    ],
                    "url": [
                        "https:\/\/notiz.blog\/2018\/06\/19\/15-jahre-wordpress\/"
                    ],
                    "category": [
                        "b2",
                        "cafelog",
                        "Jubil\u00e4um",
                        "WordPress"
                    ],
                    "publication": [
                        "notiz.Blog"
                    ],
                    "featured": [
                        "https:\/\/notiz.blog\/wp-content\/uploads\/2018\/05\/wp15.png"
                    ],
                    "author": {
                        "name": "Matthias Pfefferle",
                        "url": "https:\/\/notiz.blog\/author\/matthias-pfefferle\/",
                        "photo": "https:\/\/secure.gravatar.com\/avatar\/75512bb584bbceae57dfc503692b16b2?s=40&d=https:\/\/notiz.blog\/wp-content\/plugins\/semantic-linkbacks\/img\/mm.jpg&r=g"
                    }
                }
            }
```

**Comment by pfefferle** [comment]
also the type is missing... either we have to fix all plugins to use correct meta-data or the plugin itself should add the meta itself...

**Comment by dshanske** [comment]
I am fixing it on the Post Kinds data now

**Pull request closed without merging**
